spring:
  application:
    name: spring-web

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog
    password: catalog

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC

  flyway:
    enabled: true

  threads:
    virtual:
      enabled: true

server:
  error:
    include-message: never
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.simonegiusso.springweb: INFO
